# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Jung Woo Young
title: Curriculum Vitae

email: wyjung0731@gmail.com
email_title: Email

# phone: +82 10-7473-3569
# phone_title: Phone

website: https://github.com/wyj3569
website_title: GitHub

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: jekyllrb
# github_username:  jekyll
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: assets/images/photo.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello? My name is Jung Woo Young.
  
  I'm currently a senior student in Pusan Nat' University and my major is Computer Sciences and Engineering.

  I'm interested in topics like convergence of Artificial Intelligence and other various systems.
  Especially, I think the convergence of embedded systems and AI is a key for revival and democratization of AI technologies.

  I'm doing one term project and studying mathematics and AI topics during this summer vacation.

  Now, I'm looking for a master position in Graduate School and want to study those topics.

  Thank you for reading my self-introduction.


content:
  - title: Project # Title for the section
    layout: list # (options: list, text)
    content:
      - layout: left # (options: left, right, top, top-right, top-middle)(default: left)
        border: # Value of `weak` will display a weak border below this item. 
                          # Any other value (or no value) means no border will be displayed
        title: 2022 IoT-X <br>Capstone Design <br>Competition <hr>  # (eg. Company or Project name)
        sub_title: UWB based <br>indoor real-time location tracking <br>and calling system
        caption: (2022.05 ~ 2022.10)
        link: https://github.com/wyj3569/IGO       # (eg. https://sproogen.github.io/modern-resume-theme)(optional)
        link_text: GitHub Link               # (optional: without this link will show URL as link text)
        # additional_links: # (optional)
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >

        description: | # this will include new lines to allow paragraphs
          Our team implemented a system named "IGO" that is tracking real-time indoor location and can call between medics and patients.

          It was implemented by various systems such as Android, Django and devices like Arduino and UWB.

          I was a software project manager and did back-end server programming.

          Our team got an excellence prize at this competition.

          This was a chance for me to learn more specific and practical knowledge of my major and could cultivate collaboration ability.

          You can see details at the link.

      - layout: left
        border:
        title: Graduation Semester <br>Capstone Design <br>Term Project <hr>
        sub_title: Wi-SUN FAN mesh network based <br>Sharing Parking Lot
        caption: (2023.05 ~)
        link: 
        link_text: GitHub Link
        # additional_links: # (optional)
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          
        description: |
          Our team is implementing a sharing parking lot system using Wi-SUN FAN mesh network.

          Wi-SUN stands for Wireless Smart Utility Network. 
          
          Wi-SUN is the IPv6 sub-GHz mesh network technology for smart city and smart utility applications.

          I am a team leader and do network programming and embedded board programming.


  - title: Experience
    layout: list
    content:
      - layout: left
        boarder:
        title: 2022 <br>Engineering Education <br>FESTA <hr>
        sub_title: Judgement Activity
        caption: (2022.11)
        link: https://www.youtube.com/channel/UCKzV6rwWuevs-7yhIeb9fHw
        link_text: Link
        quote: >
          
        description: |
          This is a festival for student engineers which was held at Ilsan Kintex.

          The people who won a high-grade prize at '2022 IoT-X Capstone Design Competition' 
          got a chance to participate in this festival as a judgement.

          There were many interesting and innovative works and many passionate students.

          It was also a great chance for me to get several interesting ideas.

          You can see details at the link.

      - layout: left
        boarder:
        title: LG Aimers <hr>
        sub_title: LG group's AI Education
        caption: (2023.07 ~)
        link: https://www.lgaimers.ai/
        link_text: Link
        quote: >
          
        description: |
          I always want to learn more practical knowledge about AI and I got a chance to participate in 'LG Aimers' program.

          This program is served by LG, one of the largest manufacturing company in Republic of Korea.

          I can learn about several AI topics like supervised learning, reinforcement learning, deep learning etc.
          

  - title: Certificate
    layout: list
    content:
    - layout: top-middle
      title: Engineer Big Data Analysis
      sub_title: 
      caption: (2023.07)
      link: https://drive.google.com/file/d/17CVWnDekaMferuChmmjDixhQ84YzYSU9/view?usp=sharing
      link_text: Link
      quote: >
        
      description: |
        


  - title: Education
    layout: list
    content:
      - layout: top-middle
        title: Pusan National University
        sub_title: Department of Computer Sciences and Engineering
        caption: (2018.03 ~)
        link:
        link_text: 
        quote: >
          
        description: | 
          As I mentioned at self-introduction, my major is CSE.

          I learned not only traditional subjects such as algorithm, operation system, computer architecture but also
          artificial intelligence, machine learning and computer vision that became more important in the 4th industrial revolution.

          So I can get methodical knowledges of major.
          

  - title: A Little More About Me
    layout: text
    content: |
      I think It's important to go right way though it takes a lot of time.

      I'm a person who decides carefully, but once I make a decision, I'll never give up and can do it all days.

      Thank you for reading my CV.


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
